spring:
  application:
    name: face
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1
        #url: jdbc:mysql://10.60.10.65:3306/wyzc_om?useUnicode=true&characterEncoding=utf-8
        #username: test_user

        #password: 1234@abcd
        url: jdbc:mysql://120.79.62.89:3306/yetdwell?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false

        #                url: jdbc:mysql://127.0.:3306/yetdwell?useUnicode=true&characterEncoding=utf-8
        username: root
        password: gg5201314
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /admin/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

pdd_pro:
  pdd-key: "bbc1737d63e44e278dbffa9e96a7eca3"
  pdd-secret: "5e1a03eb561bac0c63c5efc8c1472119fc3ad405"
  pdd-access_token: "fd5d312adc6e4200bcf314cf943a287593ee3f07"
  pdd-url: "https://wj.hxksky.com"
  pdd-router-url: "https://gw-api.pinduoduo.com/api/router"
